# Help for statisticians!

Your fellow statisticians need you. They want to learn how to program in Python and have tons of calculations to do.

Very kindly, you agree to help them. Complete the missions below.

![Einstien le génie](https://wallup.net/wp-content/uploads/2018/09/30/201016-funny-albert-einstein-748x468.jpg)

In [ ]:
# Mission 1: Create a function, that simply returns the string "Hello Python"

def message():
  return "Hel"

In [ ]:
def message():
  message = "Hello Python"
  result = message
  return "Hello Python"

message = "Hello Python"
result = message
print(result)

Hello Python

In [ ]:
# Mission 2: Create a function that takes in 2 numbers as parameters, and returns a boolean indicating whether or not they are equal

In [ ]:
def numbers (num1, numb2):
  num1 = int(input("type a number"))
  num2 = int(input("type a number"))
  if num1 == num2:
    return "true"
  else:
    return "not equal"

num1 = int(input("type a number"))
num2 = int(input("type a number"))

if num1 == num2:
  print("equal")
else:
  print("not equal")

type a number2
type a number3
not equal

In [ ]:
# Mission 3: Create a function that takes a number as parameter, and returns the first 10 multiples of the number as a list
# Example: 2 -> [2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
def listes_of_n(nb):
    listes = []
    for i in range(1, 11):  # Loop from 1 to 10
        listes.append(nb * i)
    return listes

nb = int(input('Enter a number: '))
result = listes_of_n(nb)
print(result)

Enter a number: 2
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

In [ ]:
# Mission 4: Create a function that takes a string as input, and return its vowels only, preserving case.
# Example: "Antidisestablishmentarianism" -> "Aiieaieaiai"
# Example: "TO BE OR NOT TO BE" -> "OEOOOE"

In [ ]:
def vowels_only(input_string):
  vowels = "AEIOUaeiou"
  result = ""

  for char in input_string:
    if char in vowels:
      result += char

  return result

string = input("Écris un mot : ")
output = vowels_only(string)

print(output)

Écris un mot : azertyuiop
aeuio

In [ ]:
# Mission 5: Create a function that takes 2 numbers as parameters, and returns the result of a division operation.
# Test if the denominator is equal to 0 and if so, display a message that says: "You can't divide by zero".

In [ ]:
def divide_numbers(numerator, denominator):
    if denominator == 0:
        return "You can't divide by zero"
    else:
        result = numerator / denominator
        return result

numerator = int(input("Entrez un numérateur : "))
denominator = int(input("Entrez un dénominateur : "))

result = divide_numbers(numerator, denominator)
print(result)

Entrez un numérateur : 15
Entrez un dénominateur : 0
You can't divide by zero

In [ ]:
# Mission 6: First, choose two arithmetical operations (such as +, -, *, or /)
# Then, create a function that takes in 3 numbers as parameters and carries out those operations, displays a message indicating if the result is positive, negative or zero, and finally returns the result.
# If a division by zero is attempted, display an error message.

# Example with multiplication and addition:
# Calling with 0, 32, 2 will compute (0*32)+2, will display "Positive result", and return 2

# Example with division and addition:
# Calling with 21, 0, 3 will try to compute (21/0)+2, will display "Divide-by-zero error"

In [ ]:
def perform_operations(num1, num2, num3):

    if num2 == 0 or num3 == 0:
        return "division par zéro"

    addition_result = num1 + num2 / num3
    multiplication_result = num1 * num2 + num3
    division_result = num1 / num2 - num3

    return addition_result, multiplication_result, division_result

num1 = int(input("Entrez un numéro : "))
num2 = int(input("Entrez un numéro : "))
num3 = int(input("Entrez un numéro : "))

results = perform_operations(num1, num2, num3)

if "division par zéro" in str(results[0]):
    print(f"Erreur lors de l'addition : {results[0]}")
else:
    print(f"Résultat de l'addition : {results[0]}")

if "division par zéro" in str(results[1]):
    print(f"Erreur lors de la multiplication : {results[1]}")
else:
    print(f"Résultat de la multiplication : {results[1]}")

if "division par zéro" in str(results[2]):
    print(f"Erreur lors de la division : {results[2]}")
else:
    print(f"Résultat de la division : {results[2]}")

Entrez un numéro : 6
Entrez un numéro : 7
Entrez un numéro : 8
Résultat de l'addition : 6.875
Résultat de la multiplication : 50
Résultat de la division : -7.142857142857143

In [ ]:
# Mission 7: Create a function that takes a number as a parameter that corresponds to gross salary and returns the net salary for executives.
# You can specify any amount of deductions, or base them on your country's example

In [ ]:
def calculate_net_salary(gross_salary):

    deduction = 0.75

    net_salary = gross_salary * deduction

    return net_salary


gross_salary = int(input("Type your gross salary : "))
deduction =  0.75
net_salary = gross_salary * deduction
print(net_salary)

Type your gross salary : 5000
3750.0

In [ ]:
# Mission 8: Create a function that can swap the values of any two variables, such as if variable A = 1 and variable B = 2, after applying the function, variable A = 2 and B = 1

In [ ]:
def swap_values():

  A = 1
  B = 2

  A, B = B, A

  return  A ; B and B ; A

A = 1
B = 2



print('A equals: ', B)
print('B equals: ', A)

A equals:  2
B equals:  1

In [ ]:
SELECT team.name AS team_name, count(player.id) AS player_count
FROM team
INNER JOIN player ON team.id = player.team_id
INNER JOIN wizard as w on player.id = w.id
GROUP BY team.name
HAVING count(player.id) >= 14 AND SUM(player.role = "seeker") >= 3 AND SUM(player.role = "keeper") >= 1 AND SUM(player.role = "chaser") >= 1 AND SUM(player.role = "beater") >= 2
ORDER BY team.name ASC